directories:
  output: release/
  buildResources: build
productName: opendkp-log-monitor
files:
  - filter:
      - '**/*'
      - '!**/*.ts'
      - '!*.code-workspace'
      - '!LICENSE.md'
      - '!package.json'
      - '!package-lock.json'
      - '!src/'
      - '!e2e/'
      - '!hooks/'
      - '!angular.json'
      - '!_config.yml'
      - '!karma.conf.js'
      - '!tsconfig.json'
      - '!tslint.json'
win:
  icon: dist/assets/icons
  target:
    - portable
    - nsis
mac:
  icon: dist/assets/icons
  target:
    - dmg
linux:
  icon: dist/assets/icons
  target:
    - AppImage
electronVersion: 8.2.1
